namespace import -force msgcat::mcset 

# GUI labels

mcset es "Automatic reductions with IRAF" "Reduccion automática CCD con IRAF"
mcset es All Todo 
mcset es Exit Salir
mcset es File Archivo
mcset es Directory Directorio
mcset es View Ver
mcset es Purge Purgar
mcset es "Purge directory" "Purgar directorio" 
mcset es "Purge catalog" "Purgar catalogo" 
mcset es "Purge screen" "Purgar pantalla"
mcset es "IRAF logfile" "Log de IRAF"
mcset es "IRAF console" "Consola de IRAF"
mcset es "DS9 tool" "Arrancar DS9"

mcset es Calibration  Calibracion
mcset es Calibrate  Calibrar
mcset es "Masters -> Catalog" "Maestros -> Catalogo"
mcset es "Use catalog" "Usar catalogo"
mcset es "Only Science Frames" "Solo objetos"
mcset es "Only Master Files" "Solo maestros"
mcset es Images Imagenes
mcset es Average Promediar 
mcset es "Median Combine" Mediana 
mcset es Register "Con Alineado"
mcset es Help Ayuda
mcset es "About ..." "Acerca de ..."
mcset es "About TkCCDRed" "Acerca de TkCCDRed"
mcset es "TkCCDRed 1.0\nby Rafael Gonzalez\nastrorafael@yahoo.es" "TkCCDRed 1.0\npor Rafael Gonzalez\nastrorafael@yahoo.es"

mcset es "Directory does not exists:\n%s" "Directorio no existe:\n%s"
mcset es "Error in %s" "Error de %s"
mcset es "No IRAF logfile in directory\n%s" "No existe logfile de IRAF para directorio:\n%s" 
mcset es "Night %3\$s, %1\$s to %2\$s, %4\$s" "Noche del %1\$s al %2\$s de %3\$s de %4\$s"

# purge.tcl translations

mcset es "Missing subdirectory name" "Falta el nombre del subdirectorio"
mcset es "Directory %s does not exists" "El directorio %s no existe"
mcset es "Usage: purge.tcl <julian day>" "Uso: purge.tcl <dia juliano>"

# astro.tcl translations

mcset es January   Enero
mcset es February  Febrero
mcset es March     Marzo
mcset es April     Abril
mcset es May       Mayo
mcset es June      Junio
mcset es July      Julio
mcset es August    Agosto
mcset es September Septiembre
mcset es October   Octubre
mcset es November  Noviembre
mcset es December  Diciembre

# core.tcl translations

mcset es "Executing script %s" "Ejecutando script %s"
mcset es "(%s)(%s) Found: %s" "(%s)(%s) Encontrado: %s" 
mcset es "(%s)(%s) Found in catalog: %s"  "(%s)(%s) Encontrado en catalogo: %s" 
mcset es "(%s)(%s) No Master File in %s"  "(%s)(%s) No hay maestro en %s"  
mcset es "(%s)(%s) No Master File in catalog"  "(%s)(%s) No hay maestro en el catalogo"  
mcset es "(%s)(%s) No individual images"  "(%s)(%s) No hay imagenes individuales"  
mcset es "(%s)(%s) Found individual images"  "(%s)(%s) Si hay imagenes individuales"  
mcset es "(%s)(%s) Generated series: %s" "(%s)(%s) Serie generada: %s "
mcset es "(%s)(%s) Master File to generate: %s" "(%s)(%s) maestro a generar: %s"
mcset es "Classify images by resolution from %s" "Clasifica por resolucion imagenes de %s"
mcset es "No images" "No hay imagenes"
mcset es "(%s) Checking overscan zone"  "(%s) Comprobando existencia zona overscan"
mcset es "(%s) Overscan present"     "(%s) Si hay overscan"
mcset es "(%s) Overscan not present" "(%s) No hay overscan"
mcset es "Execute master files calibration first ! " "Ejecutar la calibracion de maestros primero !" 
mcset es "(%s)(%s) Making master file" "(%s)(%s) Produciendo fichero maestro"
mcset es "(%s)(%s) Nothing to combine for master file" "(%s)(%s) Nada que combinar para fich maestro"
mcset es "(%s) Invalid calibration. Darks and flats needed" "(%s) Calibracion invalida. Se necesitan darks y flats"
mcset es "(%s) Invalid calibration. Darks needed" "(%s) Calibracion invalida. Se necesitan darks"
mcset es "(%s) Calibration with Dark & Flat Dark" "(%s) Calibracion con Dark y Flat Dark"
mcset es "(%s) Calibration not implemented" "(%s) Calibracion no implementada"
mcset es "(%s) Generic calibration" "(%s) Calibracion generica"

mcset es "No subdirectory %s !"  "No existe el subdirectorio %s !"
mcset es "deleting file/subdirectory %s" "borrando fichero/subdirectorio %s"
mcset es "copying files from %s" "copiando ficheros desde %s"
mcset es "truncating file %s" "truncado fichero %s"
mcset es "No registered callback for message log" "No hay registrado un callback para el log de mensajes"
mcset es "(%s) Input list: %s" "(%s) Lista de entrada: %s"
mcset es "(%s) Output list: %s" "(%s) Lista de salida: %s"
mcset es "(%s) Reference image: %s" "(%s) Imagen referencia: %s"
mcset es "(%s) Shifts file: %s" "(%s) Fichero desplaz: %s"
mcset es "(%s) Final image: %s" "(%s) Imagen final: %s"
mcset es "(%s) Reducing list %s" "(%s) Reduciendo lista %s"
mcset es "(%s) Generating object list for reduction" "(%s) Generando lista de objetos a reducir"
mcset es "(%s) List %s" "(%s) Lista %s"
mcset es "Purge catalog subdir %s" "Purgando subdir. catalogo %s"
mcset es "(%s)(%s) Updating catalog file %s" "(%s)(%s) Copiando %s al  catalogo"
mcset es "(%s)(%s) Deleting catalog file %s" "(%s)(%s) Quitando %s del catalogo"

mcset es "N=%d. Using Sigma Clipping algorithm" "N=%d. Uso algoritmo Sigma Clipping"

mcset es "N=%d. Using Average Sigma Clipping algorithm" "N=%d. Uso algoritmo Average Sigma Clipping"

mcset es "--         INITIALIZATION DONE         --" "--        INICIALIZACION HECHA         --"

mcset es "-----   REGISTERING SEQUENCE FINISHED   -----"    "-----  TERMINA  SECUENCIA DE REGISTRADO -----"    

mcset es "-----   STARTING REGISTERING SEQUENCE   -----"    "-----  COMIENZA SECUENCIA DE REGISTRADO -----"    

mcset es "---  STARTING CALIBRATION SEQUIENCE   ---"    "--- COMIENZA SECUENCIA DE CALIBRACION ---"    
mcset es "---   CALIBRATION SEQUENCE FINISHED   ---"   "--- TERMINA  SECUENCIA DE CALIBRACION ---"     

mcset es "----    REDUCTION SEQUENCE BEGINS    ----"         "---- COMIENZA SECUENCIA DE REDUCCION ----"    

mcset es "----  REDUCTION SEQUENCE FINISHED   -----"    "---- TERMINA SECUENCIA DE REDUCCION -----"    

mcset es "-----      PURGE SEQUENCE BEGINS    -----"    "----- COMIENZA SECUENCIA DE PURGADO -----"    
mcset es "-----      PURGE SEQUENCE BEGINS    -----"    "----- COMIENZA SECUENCIA DE PURGADO -----"    

mcset es "-----    PURGE SEQUENCE FINISHED    -----"    "-----  TERMINA SECUENCIA DE PURGADO -----"    

mcset es "-----     STARTING DISPLAY SEQUENCE     -----" "----- COMIENZA SECUENCIA DE VISUALIZADO -----" 

mcset es "-----     DISPLAY  SEQUENCE FINISHED    -----" "----- TERMINA SECUENCIA DE VISUALIZADO  -----"    

mcset es "-----   STARTING COMBINING  SEQUENCE    -----" "-----    EMPIEZA SECUENCIA DE APILADO   -----"
mcset es "-----    COMBINING SEQUENCE FINISHED    -----" "-----    TERMINA SECUENCIA DE APILADO   -----"
