#!/iraf/irafbin/bin.linux/ecl.e -f

# $Id: $
# Template CL script automatically 
# generated by  TCL + template file
# Do not edit.


logver = "IRAF V2.12.2 January 2004"
set   home    = "[set cl(HOME)]/"
set   uparm   = "home$uparm/"
reset imextn  ="fxf:fits,fit,fts"
reset imtype  = fits 
flpr

# load packages

images
imutil
noao
imred
ccdred

keep

# do the work
{
	cd [set cl(basedir)]
	ccdgroups [set cl(images)] output=[set cl(output)] \
	group=ccdtype ccdtype=[set cl(ccdtype)]
	logout
}
