#!/iraf/irafbin/bin.linux/ecl.e -f

# $Id: $
# Template CL script automatically 
# generated by  TCL + template file
# Do not edit.

logver = "IRAF V2.12.2 January 2004"
set home   = "[set cl(HOME)]/"
set uparm = "home$uparm/"


# load packages

images
imutil
noao
imred
ccdred

keep

# do the work
{
	cd [set cl(basedir)]


	ccdproc.fixpix=no
	ccdproc.biassec="[set cl(biassec)]"
	ccdproc.trimsec="[set cl(trimsec)]"
	ccdproc.overscan=[set cl(overscan)]
	ccdproc.trim=[set cl(overscan)]
	ccdproc.zerocor=[set cl(zerocor)]
	ccdproc.darkcor=[set cl(darkcor)]
	ccdproc.flatcor=[set cl(flatcor)]
	ccdproc.zero="[set cl(zero)]"
	ccdproc.dark="[set cl(dark)]" 
	ccdproc.flat="[set cl(flat)]" 
	ccdproc.ccdtype="[set cl(ccdtype)]"
	ccdproc.output=""
	ccdproc.minreplace=1.
	ccdproc.interactive=no 
	ccdproc.order=1	
	
	logout
}

