#!/iraf/irafbin/bin.linux/ecl.e -f

# $Id: $
# Template CL script automatically 
# generated by  TCL + template file
# Do not edit.

logver = "IRAF V2.12.2 January 2004"
set home   = "[set cl(HOME)]/"
set uparm  = "home$uparm/"
reset imextn  ="fxf:fits,fit,fts"
reset imtype  = fits 
flpr

# load packages

images
imutil
noao
imred
ccdred

keep

# do the work
{
	cd [set cl(basedir)]

	print("\\n==================================================", >> ccdred.logfile)
	print("=              IRAF DARKCOMBINE                   ", >> ccdred.logfile)
	print("=", >> ccdred.logfile)
	print("= Directorio   base: [set cl(basedir)]", >> ccdred.logfile)
	print("= Lista  de entrada: @[set cl(input)]", >> ccdred.logfile)
	print("= Fichero de salida: [set cl(output)]", >> ccdred.logfile)
	print("==================================================\\n", >> ccdred.logfile)


	darkcombine @[set cl(input)] output="[set cl(output)]" \
	combine=average reject=minmax nlow=0 nhigh=1 scale=exposure \
	process=[set cl(process)] 
	imdelete @[set cl(input)]
	logout
}

