#!/iraf/irafbin/bin.linux/ecl.e -f

# $Id: $
# Template CL script automatically 
# generated by  TCL + template file
# Do not edit.

logver = "IRAF V2.12.2 January 2004"
set   home    = "[set cl(HOME)]/"
set   uparm   = "home$uparm/"
reset imextn ="fxf:fits,fit,fts"
reset imtype  = fits 
flpr

# load packages

images
imutil
noao
imred
ccdred

keep

# do the work
{
	cd [set cl(basedir)]

	print("==================================================\\n", >> ccdred.logfile)
	print("=              IRAF DARK CORRECTION                   \\n", >> ccdred.logfile)
	print("= Directorio  base: [set cl(basedir)]", >> ccdred.logfile)
	print("= Lista de entrada: @[set cl(inputlist)]\\n", >> ccdred.logfile)
	print("==================================================\\n", >> ccdred.logfile)

	ccdproc @[set cl(inputlist)] \
	ccdtype="" fixpix- overscan- trim- [set cl(darkcor)]      \
	zerocor- flatcor- illumcor- fringecor- readcor-           \
	dark="[set cl(dark)]"         
	logout
}

