#!/iraf/irafbin/bin.linux/ecl.e -f

# $Id: $
# Template CL script automatically 
# generated by  TCL + template file
# Do not edit.

logver = "IRAF V2.12.2 January 2004"
set home   = "[set cl(HOME)]/"
set uparm  = "home$uparm/"
reset imextn  ="fxf:fits,fit,fts"
reset imtype  = fits 
flpr

# declare tasks and packages

set ntodir = "home$nto/"
task $nto = ntodir$nto.cl

# load packages

images
imutil
noao
imred
ccdred
nto

# convenient
keep

# do the work
# assumes that the response file is erased by the TCL script first

{

	cd [set cl(basedir)]
	
	keystat("[set cl(images)]",keyword="[set cl(keyword)]")

	printf("%d;%g;%g;%g;%g\\n", keystat.N, keystat.min, keystat.max, \
		keystat.mean, keystat.stddev, > "[set cl(respfile)]")
	logout
}

